# Default values for sunny-jenkins-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

jenkins:
  image:
    repository: sunnyredhu/jenkins
    pullPolicy: IfNotPresent
    tag: "2.309-alpine-0.0.1"

service:
  type: ClusterIP         # ClusterIP, NodePort, LoadBalancer, ExternalName
  ports:
    master: 8080
    agent: 50000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

persitentVolumeClaim:
  storage: 5G
  # storageClassName: hostpath          # Docker desktop k8s cluster
  storageClassName: standard-rwo    # GKE cluster

sealedSecrets:
  jcasc:
    data:
      admin_username: ''
      admin_password: ''
    type: 'Opaque'

nodeSelector: {}

tolerations: []

affinity: {}
