apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sunny-jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: jenkins/sunny-jenkins-helm/
    repoURL: 'https://github.com/sredhu37/practice.git'
    targetRevision: dev
    helm:
      valueFiles:
      - values-dev.yaml
      values: |
        persitentVolumeClaim:
          storage: 10G
        sealedSecrets:
          jcasc:
            data:
              admin_password: AgCk16jXD0fbKZY8cHYNedBok1p30517qQwpd/h3rahPKlzwTZ4OpjQCHqWuutTk2V/Obp3EFnYwfPRylwdoaRWPWOlieg7cBRqKWvskpKmbS0GUxywfTrWET8OK79j38iMNUSpEQ/DUEX7SukfIbiMPmtBRw9utweEL9uZ2NDXlnYkXDLLgsPhYkoEVuZEGdI18wJXR+DtBzDqziRU1P8UvGlVHV/Hd5G3k09N0uvqGeoYM9/uD8QQRnR4ksQYRW0gWXue7RocRlMy5L4v63BLlRdx488Kp/DatKhP3bwD/aKSQQu45XufM0pw6Le0kRceb1Fy7zSlFRDZVKUeEX7JdGan7F8yDwKwTwPHLgiOTK5TdM7Bp+qYLhi4yrlKYCgEb8TKd47bJSwe/YYkycbv1FY1D0ysaiREq5CLJdoV9F/dPI0GWU2unYJ7GR9F3+Q4ei4aANfvGtEQEInCmtN4l57hgJrniEjXZRryx7dfbP4+9c4LxNaELDMNiGWCMPrcFDtxes8dDTmvl/+FGbDUaT3CyE2quZpWZt83waW+LumYrtlgHq2NK3zhn2G1nQ5j06bwWNbGt+cuXg2SK1rlXufy+yTOLX/XlnOFULWlqKNXabd5e+1U61li9zMwGi5W4tw+7FnX/hD+mP1JRTCl5Gw4vTQaN8gz12VfiIcjvooz8s+O0XCfMkX/ldZ4ZT0uVRbzkE4w=
              admin_username: AgALyhRNELXakbI3uJshmot29mEItiVifDFDpyzZt1nkxrBBDaMJucpHqcH7uJNRE02vUhqKtXv+XYZq0IUYDvAWnO3CkU8C66xvCRP4x9zVnkV8lgVinVZP7nLbps8QikjQb5yw48BEWI8o+JrOaa/QGCrufsDVNc4haXmdRRaa4ir6OppSRbLjuesIzMEIEjvWVJLKRronhbF49tsgnqMbM8fVSGuqXFcw5X9wUHtEqL8NBO4OQSEnRJXq9JKRVmJNDz+NXQQz+jA0y31W7x9nQrtP8kgUaQYtk4wAumbfDvtUJYlg2//y3ii3WPS4eiyeck3X59nyfJpK/jTrdDsG37A84ON2l0SVmw7QsgSpW90EynzsM+E2d4C3IeJV1hlKidg4ytk7eSdSXM5Imep/FeXDxoLFIZWCXHBHl78XqLc57yAjEJHaa2TvjdXkFb51U65fK53+5ric+bHaLFvWZrZ1fGDUJy1IGhrD/+RfBKUpE+wrr2E1CycQKi2XUyEXD6ifXrQL0WrvrBmYn7JRPp08/N88ve5JeRTeUd7AnC2WRIf9YIPhTjJepOpS0pKYeTWh2Q+UCcrXq2dK+Jpq/8cea9ndV7KRe4f9iR2vNGwwSreTFWkilk6CA+7QJf0nd9FkjxhBkc2jmnbmugpYjhhtI/IfL1jYmRf9cLZdDggWn4UcY0JS+bAClbOCgL6iehcwQ7g=
            type: 'Opaque'
