---
kind: Namespace
apiVersion: v1
metadata:
  name: jenkins
  labels:
    name: jenkins

---
kind: Namespace
apiVersion: v1
metadata:
  name: argocd
  labels:
    name: argocd

---
kind: Namespace
apiVersion: v1
metadata:
  name: resume
  labels:
    name: resume
