apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    # server: 'https://kubernetes.default.svc'
    server: 'https://35.244.2.173'              # Same k8s cluster where the controller is running
  source:
    path: argo_apps/
    repoURL: 'https://github.com/sredhu37/practice.git'
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
