apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sunny-jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: jenkins
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: jenkins/sunny-jenkins-helm/
    repoURL: 'https://github.com/sredhu37/practice.git'
    targetRevision: master
    helm:
      valueFiles:
      - values.yaml
      values: |
        persitentVolumeClaim:
          storage: 10G
        casc: |
          unclassified:
            location:
              url: "http://127.0.0.1:8080/"
          jenkins:
            authorizationStrategy:
              projectMatrix:
                permissions:
                - "Overall/Administer:admin"
                - "Overall/Read:authenticated"
            securityRealm:
              local:
                allowsSignup: true
                enableCaptcha: false
                users:
                - id: ubuntu
                  name: ubuntu
                  password: ubuntu
            remotingSecurity:
              enabled: true
