apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-master
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Release.Name }}.sunnyredhu.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-master
            port:
              number: {{ .Values.service.ports.master }}
