apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-master
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app:  {{ .Release.Name }}-master
  ports:
    - name: master
      protocol: TCP       # TCP, UDP, SCTP
      port: {{ .Values.service.ports.master }}
      targetPort: master
    - name: agent
      protocol: TCP       # TCP, UDP, SCTP
      port: {{ .Values.service.ports.agent }}
      targetPort: agent
  type: {{ .Values.service.type }}
