apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-master
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-master
  serviceName: {{ .Release.Name }}-master
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-master
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: permissionsfix
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - chown 1000:1000 /var/jenkins_home;
        volumeMounts:
        - name: {{ .Release.Name }}-home
          mountPath: /var/jenkins_home
      containers:
      - name: {{ .Release.Name }}-master
        image: {{ .Values.jenkins.image.repository }}:{{ .Values.jenkins.image.tag }}
        imagePullPolicy: {{ .Values.jenkins.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: master
        - containerPort: 50000
          name: agent
        env:
          - name: JAVA_OPTS
            value: "-Djenkins.install.runSetupWizard=false -Dcasc.reload.token=12345"     # Needs modification
          - name: CASC_JENKINS_CONFIG
            value: /var/jenkins_home/casc_config/casc.yaml
        volumeMounts:
        - name: {{ .Release.Name }}-home
          mountPath: /var/jenkins_home
        - name: {{ .Release.Name }}-casc
          mountPath: /var/jenkins_home/config_casc
      volumes:
      - name: {{ .Release.Name }}-home
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-home
      - name: {{ .Release.Name }}-casc
        configMap:
          name: {{ .Release.Name }}-casc
          items:
          - key: "casc"
            path: "casc.yaml"
